[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "@sp1-contracts/=./lib/sp1-contracts/contracts/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ultrasoundlabs/accounts/=lib/accounts/",
    "@matterlabs/zksync-contracts/=lib/v2-testnet-contracts/",
    "@forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
